---

- name: consul template - configuration
  template:
    src=consul-template.conf.j2
    dest={{consul_template_config_file_path}}
    owner={{consul_template_user}}
    group={{consul_template_group}}
    mode=0644
    backup=yes
  notify: restart consul template
