---

- name: install - group
  group:
    name={{ consul_template_group }}
    state=present
    system=yes

- name: install - user
  user:
    name={{ consul_template_user }}
    group={{ consul_template_group }}
    system=yes
    createhome=no

- name: install - directories
  file:
    state=directory
    path={{ item }}
    owner={{ consul_template_user }}
    group={{ consul_template_group }}
  with_items:
    - "{{ consul_template_install_dir }}/current"
    - "{{ consul_template_config_dir }}"
    - "{{ consul_template_log_dir }}"

- name: install - download
  get_url:
    url={{ consul_template_uri }} 
    dest={{ consul_template_download_folder }}
  register: consul_template_was_downloaded

- name: install - copy and unpack
  unarchive:
    src={{ consul_template_download_folder }}/{{ consul_template_archive }}{{ consul_template_archive_ext }}
    dest={{ consul_template_install_dir }}
    copy=no

- name: install - link current
  file:
    src={{ consul_template_install_dir }}/{{ consul_template_archive }}/{{consul_template_binary}}
    dest={{ consul_template_install_dir }}/current/{{consul_template_binary}}
    state=link
    force=yes

- name: install - link bin dir
  file:
    src={{ consul_template_install_dir }}/current/{{consul_template_binary}}
    dest=/usr/local/bin/consul-template
    state=link
    force=yes

